### ISSUE TITLE
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by sbonaime** [Seangottarun/GPXOverlay#7]
On my mac, after installation I have the following error. 
````
python3 overlay_speed.py

ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[image2 @ 0x7fbf18008a00] Could find no file with path 'temp/speed%d.png' and index in the range 0-4
temp/speed%d.png: No such file or directory
Traceback (most recent call last):
  File "/Users/bonaime/git/GPXOverlay/examples/overlay_speed.py", line 77, in <module>
    convert_overlay_to_video(frame_name_format, output_overlay_path, fps)
  File "/Users/bonaime/git/GPXOverlay/GPXOverlay/overlay.py", line 23, in convert_overlay_to_video
    ffmpeg
  File "/usr/local/lib/python3.9/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
````

**Comment by sbonaime** [comment]
It is not a ffmpeg problem. The temp directory only contains  updated_speed.html. 
png files are not created. 

by the way, maybe we could change the temp directory using import tempfile instead of creating the temp directory
````
import tempfile

temp_dir = tempfile.TemporaryDirectory()
print(temp_dir.name)
# use temp_dir, and when done:
temp_dir.cleanup()
````

**Comment by sbonaime** [comment]
Solve my problem using
`brew install wkhtmltopdf`
instead of 
`brew cask install wkhtmltopdf`

**Comment by Seangottarun** [comment]
Hi @sbonaime, thanks for checking out my project! It's a bit clunky but I'll hopefully get around to cleaning it up soon.

Just curious, what macOS version and homebrew are you using? I might be using an older version.

I also didn't know about `tempfile` and I like that idea. If you have the time, feel free to add it in with a pull request. Otherwise, I'll try to get to that some time.

**Comment by sbonaime** [comment]
I will try to add the `tempfile` adn maybe with `tempfile.SpooledTemporaryFile`
https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile
